language: golang

services:
  - docker

before_install:
  - docker pull node:14.15.1-slim
  - docker pull golang:1.16.3
  - docker pull ubuntu:20.04
  - docker images -a

script:
  - docker build --tag youjianglong/grafana:dev -f Dockerfile.ubuntu .
