language: golang

services:
  - docker

before_install:
  - docker pull node:14.15.5-alpine3.13
  - docker pull golang:1.16.1-alpine3.13
  - docker pull alpine:3.13
  - docker images -a

script:
  - docker build --tag youjianglong/grafana:dev .
